### ISSUE TITLE
Problem running split in CONCH/CLAM environment

### ISSUE THREAD

**Issue by suminwei** [mahmoodlab/CLAM#248]
Hi,
I'm running into the following error when trying to run create_splits_seq.py in a conda environment with CONCH and CLAM installed:

python create_splits_seq.py --task task_2_tumor_subtyping --seed 1 --label_frac 1 --k 10

`/home/liw165/.local/lib/python3.10/site-packages/torch/cuda/__init__.py:118: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11020). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/n/data1/dfci/medicine/beltran/lab/lwei/Software/CLAM_install/CLAM/create_splits_seq_MLN_CONCH.py", line 35, in <module>
    dataset = Generic_WSI_Classification_Dataset(csv_path = '/n/data1/dfci/medicine/beltran/lab/lwei/ML/analysis/CLAM/MLN/training_391_CONCH/dataset_csv/tumour_subtyping_clean.csv',
  File "/n/data1/dfci/medicine/beltran/lab/lwei/Software/CLAM_install/CLAM/datasets/dataset_generic.py", line 76, in __init__
    self.patient_data_prep(patient_voting)
  File "/n/data1/dfci/medicine/beltran/lab/lwei/Software/CLAM_install/CLAM/datasets/dataset_generic.py", line 104, in patient_data_prep
    label = stats.mode(label)[0]
  File "/home/liw165/.local/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py", line 531, in axis_nan_policy_wrapper
    res = hypotest_fun_out(*samples, **kwds)
  File "/home/liw165/.local/lib/python3.10/site-packages/scipy/stats/_stats_py.py", line 522, in mode
    raise TypeError(message)
TypeError: Argument `a` is not recognized as numeric. Support for input that cannot be coerced to a numeric array was deprecated in SciPy 1.9.0 and removed in SciPy 1.11.0. Please consider `np.unique`.`

**Comment by fedshyvana** [comment]
Hi, sorry for the late reply, hopefully the issue has already been resolved. If not, please feel free to follow up!

**Comment by WinterPan2017** [comment]
The issue is still exits. Actually the issue is related the scipy. Scipy.stat only accept numeric list from scipy 1.9.0. If the label is str, the issue raise. I solve issue by replace
