### ISSUE TITLE
Error while executing main.py

### ISSUE THREAD

**Issue by JTatsuya** [mahmoodlab/CLAM#268]
Hi, I am reproducing this project on wins and it is failing to build the .pt file via dataset_generic.py, do you know what is the reason. The exact error message is below:

Traceback (most recent call last):
  File "D:\Github\CLAM-master\main.py", line 210, in <module>
    results = main(args)
  File "D:\Github\CLAM-master\main.py", line 49, in main
    results, test_auc, val_auc, test_acc, val_acc  = train(datasets, i, args)
  File "D:\Github\CLAM-master\utils\core_utils.py", line 186, in train
    train_loop_clam(epoch, model, train_loader, optimizer, args.n_classes, args.bag_weight, writer, loss_fn)
  File "D:\Github\CLAM-master\utils\core_utils.py", line 236, in train_loop_clam
    for batch_idx, (data, label) in enumerate(loader):
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\_utils.py", line 705, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Github\CLAM-master\dataset_modules\dataset_generic.py", line 339, in __getitem__
    features = torch.load(full_path)
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Huicheng\anaconda3\envs\clam\lib\site-packages\torch\serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Github\\CLAM-master\\Extracted_feature\\tumor_vs_normal_resnet_features\\ptt_files\\slide_025.pt'

I'd really appreciate it if I could hear from you.

**Comment by fedshyvana** [comment]
this doesn't look right: 'Extracted_feature\tumor_vs_normal_resnet_features\ptt_files\slide_025.pt', the folder name should be 'pt_files' i believe. Have you verified that all the feature files are present / in the correct location?

**Comment by fedshyvana** [comment]
Feel free to re-open if you need more help.
