### ISSUE TITLE
shape incompatibility in score2percentile function in create_heatmaps

### ISSUE THREAD

**Issue by cagankpln** [mahmoodlab/CLAM#282]
Hello, when we were running the create_heatmaps.py code, we got this error: 
Traceback (most recent call last):
  File "/home/galen/CLAM/create_heatmaps.py", line 369, in <module>
    compute_from_patches(wsi_object=wsi_object, 
  File "/home/galen/CLAM/vis_utils/heatmap_utils.py", line 82, in compute_from_patches
    A[score_idx] = score2percentile(A[score_idx], ref_scores)
ValueError: could not broadcast input array from shape (15882,) into shape (1,)

We noticed that the shape of the ref_scores is [15882, 1], so we resolved this error by flattening the ref_scores. We also noticed that there are several closed issues mentioning this problem with the solution similar to ours. Since these issues are closed, we doubted ourselves whether we made a previous mistake in the pipeline that caused this error. Or are the codes not fixed?

**Comment by Adali35** [comment]
Hi I am having the same problem, I do not know why we need to reshape the ref_scores and I am not sure whether it is a serious problem to lean on. Some clarification would be very nice ! :)
