### ISSUE TITLE
Heatmap visualization

### ISSUE THREAD

**Issue by AishwaryaAllada** [mahmoodlab/CLAM#59]
Hello,

Thank you for providing the script for the visualization of the heatmap of a WSI.

Following this, [https://github.com/mahmoodlab/CLAM#Heatmap-Visualization], I got the error as mentioned below. 

Traceback (most recent call last):
  File "create_heatmaps.py", line 164, in <module>
    model =  initiate_model(model_args, ckpt_path)
  File "/mnt/ntfs-d/akallada/Desktop/CLAM/utils/eval_utils.py", line 36, in initiate_model
    ckpt = torch.load(ckpt_path)
  File "/home/akallada/anaconda3/envs/clam/lib/python3.7/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'heatmaps/demo/ckpts/s_0_checkpoint.pt'

Any leads could be helpful. Thank you in advance.

**Comment by fedshyvana** [comment]
Hi, looks like gitignore prevented uploading the ckpt file - it should be fixed now if you pull the update.
