### ISSUE TITLE
Empty filtered coordinates when running create_heatmaps.py 

### ISSUE THREAD

**Issue by dkoen** [mahmoodlab/CLAM#75]
The output is as follows (note I added logging info): 

```
Init Model
CLAM_SB(
  (attention_net): Sequential(
    (0): Linear(in_features=1024, out_features=512, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.25, inplace=False)
    (3): Attn_Net_Gated(
      (attention_a): Sequential(
        (0): Linear(in_features=512, out_features=256, bias=True)
        (1): Tanh()
        (2): Dropout(p=0.25, inplace=False)
      )
      (attention_b): Sequential(
        (0): Linear(in_features=512, out_features=256, bias=True)
        (1): Sigmoid()
        (2): Dropout(p=0.25, inplace=False)
      )
      (attention_c): Linear(in_features=256, out_features=1, bias=True)
    )
  )
  (classifiers): Linear(in_features=512, out_features=2, bias=True)
  (instance_classifiers): ModuleList(
    (0): Linear(in_features=512, out_features=2, bias=True)
    (1): Linear(in_features=512, out_features=2, bias=True)
  )
  (instance_loss_fn): CrossEntropyLoss()
)
Total number of parameters: 790791
Total number of trainable parameters: 790791
Done initializing model!
Slide name: 46950
Slide ext: .svs

processing:  46950.svs
slide id:  46950
top left:  None  bot right:  None
seg_level: -1
sthresh: 15
mthresh: 11
close: 2
use_otsu: False
keep_ids: []
exclude_ids: []
a_t: 1
a_h: 1
max_n_holes: 2
vis_level: -1
line_thickness: 50
Initializing WSI object
Slide path: /sc/arion/projects/tauomics/PART_images/Hippocampus_AT8_stain/46950.svs
Done!
h5 path: heatmaps/heatmap_raw_results/HEATMAP_OUTPUT_ARTAG/ARTAG/46950/46950.h5
processing 0/2 contours
Bounding Box: 42326 14948 1521 1217
Contour Area: 301824.0
Extracted 1 coordinates
coord_results: {}
processing 1/2 contours
Bounding Box: 29924 13011 2993 4755
Contour Area: 738128.0
Extracted 1 coordinates
coord_results: {}
filtered_coords: []
```  

Which results in the following error: 

```
Traceback (most recent call last):
  File "create_heatmaps.py", line 298, in <module>
    ref_scores=None)				
  File "/sc/arion/projects/tauomics/danielk/ARTAG_CLAM/CLAM/vis_utils/heatmap_utils.py", line 54, in compute_from_patches
    roi_dataset = Wsi_Region(wsi_object, **wsi_kwargs)
  File "/sc/arion/projects/tauomics/danielk/ARTAG_CLAM/CLAM/datasets/wsi_dataset.py", line 102, in __init__
    coords=np.vstack(filtered_coords)
  File "<__array_function__ internals>", line 6, in vstack
  File "/hpc/users/koenid03/.conda/envs/clam/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
``` 

The code that is failing is 

```python
if not os.path.isfile(h5_path) :
	_, _, wsi_object = compute_from_patches(wsi_object=wsi_object, 
									model=model, 
									feature_extractor=feature_extractor, 
									batch_size=exp_args.batch_size, **blocky_wsi_kwargs, 
									attn_save_path=None, feat_save_path=h5_path, 
									ref_scores=None)	
``` 

which fails at 

```python 
for cont_idx, contour in enumerate(wsi_object.contours_tissue): 
            print('processing {}/{} contours'.format(cont_idx, len(wsi_object.contours_tissue)))
            cont_check_fn = get_contour_check_fn(contour_fn, contour, self.ref_size[0], center_shift)
            coord_results, _ = wsi_object.process_contour(contour, wsi_object.holes_tissue[cont_idx], level, '', 
                            patch_size = patch_size[0], step_size = step_size[0], contour_fn=cont_check_fn,
                            use_padding=True, top_left = top_left, bot_right = bot_right)
            print('coord_results:', coord_results)
            if len(coord_results) > 0:
                filtered_coords.append(coord_results['coords'])
        print('filtered_coords:', filtered_coords)
        coords=np.vstack(filtered_coords)
```

**Comment by fedshyvana** [comment]
well it looks like the segmentation/patching didn't detect any tissue patches in your WSI. did you check the segmentation mask to make sure that it's been segmented properly? if not, you can try to use a different preset csv or manually specify your own paramters in the process list csv file.

**Comment by dkoen** [comment]
Could this have to do with the location of the patches? They aren't located in the traditional place but I am having a hard time figuring out where to feed in the location of the patches (if they are needed)? 

Where can I check the segmentation mask? 

I looked at the preset csvs but I don't see why they would be having a problem.

**Comment by fedshyvana** [comment]
https://github.com/mahmoodlab/CLAM/blob/master/heatmaps/configs/config_template.yaml
It depends on where you specified to be your "raw_save_dir" - there should be a folder for each slide, which contains masks, and blocky heatmaps (if successfully created).

**Comment by dkoen** [comment]
for the given slide there are two files 

[slide_id]_mask.jpg 
and
[slide_id]_mask.pkl 

![image](https://user-images.githubusercontent.com/10600425/128204126-edcacb8d-6212-4778-bf4f-9b9f4431c309.png)

is the jpg

**Comment by fedshyvana** [comment]
but also, all of the models presented in the paper were developed based on HE and targets HE, whereas your WSI does not look like an HE image. Did you already train a model based on whatever stain this is, and are trying to apply it? Otherwise if you're trying to play with the code and see how it works, I would find an actual HE WSI instead.

**Comment by dkoen** [comment]
I did train a model based on this. I'm guessing I have my config yaml written incorrectly and am using the wrong data dir? I have it set to the original svs files

**Comment by fedshyvana** [comment]
setting to your original svs files should be fine - given what i see, as mentioned above, you would just need to use another set of segmentation paramters or preset that you had success with when you initially processed your slides (either change the preset or process_list in .yaml file).

**Comment by dkoen** [comment]
Now it is failing further down on computing blend 

```
computing blend
using block size: 1024 x 1024
processing 0/2 contours
Bounding Box: 42230 14756 1633 1409
Contour Area: 322432.0
Extracted 1 coordinates
coord_results: {}
processing 1/2 contours
Bounding Box: 29876 13011 3041 4755
Contour Area: 757456.0
Extracted 0 coordinates
coord_results: {}
filtered_coords: []
```
This seems to be an error with a call to the same function: 

```
Traceback (most recent call last):
  File "create_heatmaps.py", line 376, in <module>
    attn_save_path=save_path,  ref_scores=ref_scores)
  File "/sc/arion/projects/tauomics/danielk/ARTAG_CLAM/CLAM/vis_utils/heatmap_utils.py", line 54, in compute_from_patches
    roi_dataset = Wsi_Region(wsi_object, **wsi_kwargs)
  File "/sc/arion/projects/tauomics/danielk/ARTAG_CLAM/CLAM/datasets/wsi_dataset.py", line 102, in __init__
    coords=np.vstack(filtered_coords)
  File "<__array_function__ internals>", line 6, in vstack
  File "/hpc/users/koenid03/.conda/envs/clam/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
``` 

Is this another value I should change in the preset csv? Sorry I am not familiar with the values in there

**Comment by dkoen** [comment]
I edited both m thresh  and s thresh and it appears to be running now

**Comment by dkoen** [comment]
Thank you for your help!

**Comment by Tejussurendran** [comment]
@dkoen hi, I am also trying to do segmentation on AT8 based patches, I was wondering if you ever found a good balance of parameters to use to get good segmentations?
