### ISSUE TITLE
Patches and Stitches folder empty but images appear in masks

### ISSUE THREAD

**Issue by DeepLearningCoder** [mahmoodlab/CLAM#79]
I am getting an empty folders for patches and stitches but I get images inside the masks folder after I ​run:
`python create_patches_fp.py --source DATA_DIRECTORY --save_dir RESULTS_DIRECTORY --patch_size 256 --seg --patch --stitch 
`
This is the output I am seeing:
```
progress: 0.80, 4/5
processing image4.tif
Creating patches for:  Single images\image4.tif
Total number of contours to process:  0
segmentation took 0.34007692337036133 seconds
patching took 0.0010008811950683594 seconds
stitching took -1 seconds
average segmentation time in s per slide: 0.3388978004455566
average patching time in s per slide: 0.00020017623901367188
average stiching time in s per slide: -1.0
```

The images in the mask folder do not appear to have any annotations.  Is this an issue with thresholding? I tried changing the values of `sthresh` and `mthresh` in `create_patches_fp.py` to very small and very large numbers but I keep getting empty patches and stitches folders. Any suggestions would be appreciated!

**Comment by fedshyvana** [comment]
Try --preset bwh_biopsy.csv and if not, lowering both a_h and a_t to 1 probably also works. The issue is likely with the area threshold on detected contours of interest, default values are too big if your images are small.

**Comment by fedshyvana** [comment]
How big are your images? might also want to use smaller patches (e.g. --patch_size 128, --step_size 128 or something)

**Comment by DeepLearningCoder** [comment]
Thank you very much! I lowered a_h and a_t to 1 and it looks like it's processing some images now. When I run the code without `--patch` and `--stitch`, I get masks with some green overlay surrounding the tissue.

However, when I run with `--patch` and `--stitch`, I get the following error: 

```
progress: 0.00, 0/5
processing image10217, w=3346, h=3346).tif
Creating patches for:  Single images\image10217, w=3346, h=3346) ...
Total number of contours to process:  1
Bounding Box: 118 0 3185 3346
Contour Area: 7060274.0
Extracted 131 coordinates
Traceback (most recent call last):
  File "create_patches_fp.py", line 307, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "create_patches_fp.py", line 196, in seg_and_patch
    file_path, patch_time_elapsed = patching(WSI_object = WSI_object,  **current_patch_params,)
  File "create_patches_fp.py", line 36, in patching
    file_path = WSI_object.process_contours(**kwargs)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\wsi_core\WholeSlideImage.py", line 385, in process_contours
    save_hdf5(save_path_hdf5, asset_dict, attr_dict, mode='w')
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\wsi_core\wsi_utils.py", line 55, in save_hdf5
    file = h5py.File(output_path, mode)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'C:/Users/user/Downloads/images/Processed images\patches\Single images\image1
0217, w=3346, h=3346).h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)
```

Do you know what might be happening here? My images are 3346x3346 pixels.

**Comment by fedshyvana** [comment]
Not exactly sure.. your write path "C:/Users/user/Downloads/images/Processed images\patches\Single images\image1
0217, w=3346, h=3346).h5" looks quite funky lol maybe it's causing some issue for the script to point to the correct path? 
Maybe try deleting the entire output folder, and rerunning it again. If it still doesn't work, maybe try renaming your folders and images to get rid of the space characters.

**Comment by DeepLearningCoder** [comment]
Ah sorry I was just shortening some file names for my question and didn't delete a part of it. But I did shorten the actual file names and deleted the output folder but am still seeing this message.

```
progress: 0.00, 0/5
processing image1.tif
Creating patches for:  Single images\image1 ...
Total number of contours to process:  1
Bounding Box: 0 0 3278 3346
Contour Area: 7043017.0
Extracted 132 coordinates
Traceback (most recent call last):
  File "create_patches_fp.py", line 307, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "create_patches_fp.py", line 196, in seg_and_patch
    file_path, patch_time_elapsed = patching(WSI_object = WSI_object,  **current_patch_params,)
  File "create_patches_fp.py", line 36, in patching
    file_path = WSI_object.process_contours(**kwargs)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\wsi_core\WholeSlideImage.py", line 385, in process_contours
    save_hdf5(save_path_hdf5, asset_dict, attr_dict, mode='w')
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\wsi_core\wsi_utils.py", line 55, in save_hdf5
    file = h5py.File(output_path, mode)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\h5py\_hl\files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'C:/Users/user/Downloads/images/Processed images\patches\Single images\image1.h5', errno = 2, error message = 'No such file or direc
tory', flags = 13, o_flags = 302)
```

**Comment by fedshyvana** [comment]
does "C:/Users/user/Downloads/images/Processed images\patches\Single images\" exist in your system then? Like can you cd to it and create files in there without issue? I must admit I only use linux so it's weird for me to see both "/" and "\" in a file path but maybe that's ok for windows.

**Comment by DeepLearningCoder** [comment]
Yeah I'm still able to create files in that directory. It's very weird to me too. I input it with all forward slashes and I'm not sure why some of them change. I input:
```
python create_patches_fp.py --source "C:/Users/user/Downloads/images/Single images" --save_dir "C:/Users/user/Downloads/images/Processed images" --patch_size 256 --seg --patch --stitch 
```

**Comment by DeepLearningCoder** [comment]
Oh it does run through all of my images! but then it still results in empty stiches and patches folders. The masks seem to have a green overlay so it does look like there's some progress. I now see this as the output for each image:
```
progress: 0.80, 4/5
processing image5.tif
Creating patches for:  C:\Users\user\Downloads\images\Single images\image5 ...
Total number of contours to process:  1
Bounding Box: 0 65 3264 3281
Contour Area: 6789559.5
Extracted 123 coordinates
segmentation took 0.43802571296691895 seconds
patching took 0.6981906890869141 seconds
stitching took -1 seconds
average segmentation time in s per slide: 0.41318163871765134
average patching time in s per slide: 0.6933202743530273
average stiching time in s per slide: -1.0
```

I also tried it with ```--preset bwh_biopsy.csv``` but then got this:

```
progress: 0.00, 0/10
processing image1.h5
Traceback (most recent call last):
  File "create_patches_fp.py", line 307, in <module>
    process_list = process_list, auto_skip=args.no_auto_skip)
  File "create_patches_fp.py", line 185, in seg_and_patch
    WSI_object, seg_time_elapsed = segment(WSI_object, current_seg_params, current_filter_params)
  File "create_patches_fp.py", line 25, in segment
    WSI_object.segmentTissue(**seg_params, filter_params=filter_params)
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\wsi_core\WholeSlideImage.py", line 144, in segmentTissue
    img = np.array(self.wsi.read_region((0,0), seg_level, self.level_dim[seg_level]))
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\openslide\__init__.py", line 375, in read_region
    [d + 1 for d in image_bottomright])
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\PIL\Image.py", line 1162, in crop
    self.load()
  File "C:\Users\user\PycharmProjects\melanoma_pathology_clam\melanoma_pathology_clam\lib\site-packages\PIL\ImageFile.py", line 325, in load
    raise IOError("cannot find loader for this %s file" % self.format)
OSError: cannot find loader for this HDF5 file
```

**Comment by fedshyvana** [comment]
wait, why do you have a image1.h5? that's the .h5 patch file right? so by default it should be saved to the "patches" folder but somehow it's now in the same folder as your images (notice number of files to process went from 5 ---> 10)

**Comment by DeepLearningCoder** [comment]
I see, thank you very much!
